### ISSUE TITLE
Default branch problems

### ISSUE THREAD

**Issue by tbreeds** [yaboot/yaboot#1]
Why does the GitHub UI insist that the default branch is `1.3.15-merge`, at least that's the one it shows when you go to https://github.com/yaboot/yaboot

**Comment by mpe** [comment]
You should be able to change the default branch at https://github.com/yaboot/yaboot/settings/branches ?

**Comment by tbreeds** [comment]
Yup I did that.  I needed to do it multiple times and then wait for it to propagate through the multiple frontends
